// shared/glossary-data.js
// All terms: level is 'grad', 'res', or 'frontier'. No 'ug' — content is graduate+ only.
// Modules augment with: Object.assign(window.GLOSS = window.GLOSS || {}, { termKey: {...} });

window.GLOSS = {
  // ── Property label terms (shown in molecule modal prop rows) ──
  'resolution':     { term:'Resolution (cryo-EM / X-ray)', level:'grad', def:'Minimum resolvable distance in Angstroms (Å). <2.5 Å = near-atomic (individual atoms visible). 2.5–3.5 Å = medium (secondary structure clear). >4 Å = low (domain arrangement only). Nobel structures typically 2.5–3.5 Å.' },
  'kd':             { term:'Dissociation constant (Kd)', level:'grad', def:'Equilibrium binding affinity: Kd = [A][B]/[AB]. Lower Kd = tighter binding. pM (10⁻¹²) = antibody-antigen; nM = drug-receptor typical; μM = weak/transient. eIF4E-m7GTP Kd ~2 nM.' },
  'xlogp':          { term:'XLogP (lipophilicity)', level:'grad', def:'Calculated partition coefficient (octanol/water). XLogP > 5 = too lipophilic (poor solubility). XLogP < 0 = hydrophilic. Lipinski rule: ≤ 5. Governs membrane permeability and oral bioavailability.' },
  'pka':            { term:'Apparent pKa (ionizable lipid)', level:'res', def:'pH at which the ionizable lipid is 50% protonated. Optimal pKa for LNP ~6.2–6.8: neutral at plasma pH 7.4 (low toxicity), cationic at endosomal pH 5.5 (membrane disruption and mRNA escape).' },
  'tpsa':           { term:'Topological Polar Surface Area (TPSA)', level:'grad', def:'Sum of surface areas of polar atoms. TPSA > 140 Å² = poor CNS penetration. TPSA < 60 Å² = good oral absorption. Used in Veber rules for oral bioavailability prediction alongside rotatable bond count.' },
  'hbd':            { term:'H-Bond Donors (HBD)', level:'grad', def:'Count of NH and OH groups capable of donating hydrogen bonds. Lipinski rule: ≤ 5. Excess HBDs reduce membrane permeability by stabilizing aqueous solvation shell around molecule.' },
  'hba':            { term:'H-Bond Acceptors (HBA)', level:'grad', def:'Count of N and O atoms capable of accepting hydrogen bonds. Lipinski rule: ≤ 10. Combined with HBD, governs aqueous solubility vs membrane permeability balance.' },
  'cancer relevance': { term:'Cancer relevance', level:'res', def:'Degree to which this molecule or pathway is implicated in oncogenesis, tumor progression, or therapeutic targeting. eIF4E is overexpressed in >30% of human cancers; mTORC1 hyperactivation is among the most common oncogenic alterations.' },
  'biodegradable':  { term:'Biodegradability (lipids)', level:'grad', def:'Ionizable lipids with ester bonds in their tails are hydrolyzed by plasma and hepatic esterases, generating metabolites cleared renally. Non-biodegradable lipids accumulate in liver — critical safety distinction for repeat dosing of mRNA therapeutics.' },

  // ── Chip / badge text terms ──
  'translation initiation': { term:'Translation initiation', level:'grad', def:'Rate-limiting step in eukaryotic protein synthesis. The 43S pre-initiation complex (40S + eIF2-GTP-Met-tRNA) scans 5\'UTR for AUG start codon. Cap-dependent: requires eIF4E binding m7G cap. Rate controlled by eIF2α phosphorylation (integrated stress response) and mTORC1 activity.' },
  'm7g cap':        { term:'m7G cap (5\' cap)', level:'grad', def:'7-methylguanosine linked 5\'→5\' to mRNA via triphosphate bridge. Recognized by eIF4E (cytoplasmic translation) and CBP20/80 (nuclear export/splicing). Required for cap-dependent translation. Absent in HCV (IRES-dependent) and mitochondrial mRNAs.' },
  'cap reader':     { term:'Cap reader / cap-binding protein', level:'grad', def:'Protein containing a cap-binding domain that recognizes m7G via pi-stacking between conserved tryptophan residues (eIF4E: W56 and W102). Selectivity for m7G over unmethylated G is ~100-fold. eIF4E is rate-limiting for cap-dependent translation.' },
  'tlr evasion':    { term:'TLR evasion (mRNA)', level:'res', def:'Strategy to prevent exogenous mRNA from activating innate immune Toll-like receptors (TLR3, TLR7, TLR8). Pseudouridine/m1Ψ modification sterically occludes the TLR binding groove. Critical for therapeutic mRNA — unmodified mRNA induces type I interferon response degrading the transcript before translation.' },
  'endosomal escape': { term:'Endosomal escape', level:'res', def:'Rate-limiting step in LNP-mediated mRNA delivery. After endocytosis, LNPs must rupture the endosomal membrane before lysosomal acidification (pH <5) degrades cargo. Ionizable lipids achieve ~1-2% escape efficiency — sufficient due to ribosomal amplification of protein output. Key determinant of potency.' },
  'structural protein': { term:'Structural protein (virus)', level:'grad', def:'Viral protein forming the physical particle architecture (capsid, envelope, spike). In SARS-CoV-2: S (spike), E (envelope), M (membrane), N (nucleocapsid). Spike is the sole mRNA vaccine antigen — its prefusion conformation contains the dominant neutralizing epitopes.' },
  'vaccine antigen': { term:'Vaccine antigen', level:'grad', def:'Molecular target chosen to elicit protective immunity. For mRNA vaccines: the SARS-CoV-2 spike protein (prefusion-stabilized). Selection criteria: surface-exposed, abundant, functional conservation across strains, accessible to neutralizing antibody epitopes, amenable to stabilization.' },
  'lnp delivery':   { term:'LNP delivery platform', level:'res', def:'Lipid nanoparticle system enabling in vivo mRNA delivery. Standard 4-component: ionizable lipid (mRNA binding), DSPC (bilayer), cholesterol (fusion), PEG-lipid (stealth). Intramuscular injection leads to local expression + dendritic cell uptake. Liver tropism via ApoE adsorption enables hepatic applications.' },
  'Nobel 2023':     { term:'Nobel Prize in Medicine 2023', level:'grad', def:'Awarded to Katalin Karikó and Drew Weissman for discoveries enabling effective mRNA vaccines against COVID-19. Specifically honored: nucleoside base modification (pseudouridine) suppressing innate immune activation of therapeutic mRNA. Combined with LNP delivery technology.' },
  'rbd-ace2 binding': { term:'RBD–ACE2 binding', level:'res', def:'Interaction between the SARS-CoV-2 spike receptor-binding domain (RBD, residues 319–541) and human ACE2. Kd ~15 nM for SARS-CoV-2 vs ~200 nM for SARS-CoV-1, explaining higher transmissibility. Furin cleavage at S1/S2 is required for full activation.' },

  // ── Core biology terms ──
  'pd1':            { term:'PD-1 (PDCD1)', level:'res', def:'Programmed cell death protein 1 — inhibitory receptor on activated T cells. Binds PD-L1/PD-L2 on tumor cells and APCs, delivering ITIM/ITSM-mediated suppressive signals. Target of nivolumab and pembrolizumab. 2018 Nobel.' },
  'ctla4':          { term:'CTLA-4', level:'res', def:'Cytotoxic T-lymphocyte antigen 4 — constitutively expressed on Tregs, transiently upregulated on activated T cells. Competes with CD28 for CD80/CD86 (B7) ligands with ~10-20× higher affinity. Attenuates T cell priming in lymph node. Target of ipilimumab. 2018 Nobel.' },
  'lnp':            { term:'Lipid nanoparticle (LNP)', level:'grad', def:'~80-100 nm delivery nanoparticle for mRNA therapeutics. Four components: (1) ionizable lipid — mRNA binding and endosomal escape; (2) DSPC — bilayer stability; (3) cholesterol — fusion; (4) PEG-lipid — stealth and colloidal stability. Ionizable lipid pKa ~6.6 is the key design parameter.' },
  'm1psi':          { term:'N1-methylpseudouridine (m1Ψ)', level:'res', def:'Nucleoside modification replacing all uridines in therapeutic mRNA. The N1-methyl group occludes the TLR3/7/8 binding groove abolishing innate immune activation. Paradoxically increases ribosome processivity ~10×. The Karikó/Weissman insight that enabled clinical mRNA therapeutics. 2023 Nobel.' },
  'codon_opt':      { term:'Codon optimization', level:'grad', def:'Replacing synonymous codons with those preferred by human ribosomes, maximizing translational speed and reducing ribosome stalling. Can increase protein output 10× for therapeutic mRNA. LinearDesign and CodonBERT (ML models) now outperform rule-based approaches by jointly optimizing stability (MFE) and efficiency.' },
  'gcreaction':     { term:'Germinal center reaction', level:'res', def:'Iterative affinity maturation in lymph node B cell follicles. B cells expressing higher-affinity BCR variants are selected; somatic hypermutation generates diversity. mRNA vaccines drive unusually strong GC reactions vs protein subunit vaccines, correlating with durable antibody responses.' },
  'prefusion':      { term:'Prefusion stabilization (2P)', level:'res', def:'K986P/V987P proline substitutions in SARS-CoV-2 spike heptad repeat 1 — from the McLellan lab. Lock the trimer in its prefusion conformation post-recombinant expression. Without 2P, spike undergoes post-fusion collapse, losing the RBD and NTD neutralizing epitopes. Used in all approved COVID vaccines.' },
  'hif1a':          { term:'HIF-1α', level:'grad', def:'Hypoxia-inducible factor 1α. Continuously synthesized under normoxia but immediately hydroxylated by PHD enzymes (using O₂ as substrate) → VHL recognition → ubiquitination → 26S proteasomal degradation. Under hypoxia: PHD inactive → HIF-1α accumulates → transcribes VEGF-A, EPO, LDHA, PDK1.' },
  'vhl':            { term:'VHL (pVHL)', level:'grad', def:'Von Hippel-Lindau tumor suppressor. Component of the CRL2-VHL E3 ubiquitin ligase. Recognizes hydroxylated prolines P402 and P564 on HIF-1α via its β-domain. Loss-of-function mutations in >90% of clear-cell renal carcinoma — the oncogenic mechanism. 2019 Nobel.' },
  'phd':            { term:'PHD enzymes (EGLN1-3)', level:'res', def:'Prolyl hydroxylase domain enzymes — O₂/2-OG/Fe²⁺-dependent dioxygenases. PHD2 (EGLN1) is the primary HIF-1α hydroxylase (P564). Activity directly proportional to O₂ concentration — the molecular O₂ sensor. Inhibited by 2-OG competitors (succinate, fumarate from IDH/SDH mutations in cancer). 2019 Nobel.' },
  'atg':            { term:'ATG proteins', level:'grad', def:'Autophagy-related gene products (~20 core). ULK1 complex: initiation kinase released by mTORC1 inhibition. PI3K complex (VPS34/Beclin-1/ATG14): PI3P generation at omegasome. ATG5-ATG12/ATG16L1: E3 ligase conjugating LC3-I to PE → LC3-II. ATG9: lipid scramblase for phagophore membrane expansion. 2016 Nobel.' },
  'lc3':            { term:'LC3/ATG8 (LC3-II)', level:'grad', def:'Ubiquitin-like modifier covalently attached to PE (phosphatidylethanolamine) on autophagosome inner and outer membranes. LC3-I (cytosolic) → LC3-II (membrane-bound) conversion is the canonical autophagosome assay. LC3-II recruits autophagy receptors (p62/SQSTM1) via LIR (LC3-interacting region) motifs. 2016 Nobel.' },
  'microrna':       { term:'microRNA (miRNA)', level:'grad', def:'~22 nt endogenous non-coding RNA. Processed from pri-miRNA (Drosha/DGCR8) → pre-miRNA (Dicer) → miRNA duplex → RISC loading (AGO2). Guide strand base-pairs 3\'UTR of target mRNAs: perfect complementarity = cleavage; imperfect = translational repression + deadenylation. ~2,500 human miRNAs, >60% of coding genes regulated. 2024 Nobel.' },
  'rnai':           { term:'RNA interference (RNAi)', level:'grad', def:'Post-transcriptional gene silencing by small RNAs loaded into RISC. AGO2 is the catalytic slicer for siRNA. miRNA uses AGO1-4. Harnessed therapeutically: inclisiran (siRNA for PCSK9/LDL-C), givosiran (ALAS1), lumasiran (HAO1). 2006 Fire/Mello Nobel.' },
  'trpv1':          { term:'TRPV1', level:'grad', def:'Transient receptor potential vanilloid 1 — tetrameric nonselective cation channel (Ca²⁺/Na⁺/K⁺). Gated by heat >43°C, capsaicin (vanilloid pocket in TM4-TM5), protons (pH<6), and endocannabinoids. Located on unmyelinated C-fiber nociceptors. Ca²⁺ influx triggers action potential. 2021 Nobel.' },
  'piezo2':         { term:'PIEZO2', level:'grad', def:'Mechanosensitive ion channel — homotrimer of ~2,521 aa/subunit with 38 transmembrane helices per subunit. Gated by membrane tension during cell deformation. On dorsal root ganglion neurons: mediates touch discrimination, proprioception, breathing-triggered Hering-Breuer reflex. PIEZO2 mutations cause FADS and proprioceptive ataxia. 2021 Nobel.' },
  'clock_bmal1':    { term:'CLOCK:BMAL1 heterodimer', level:'grad', def:'Core positive limb of circadian feedback loop. CLOCK:BMAL1 bHLH-PAS heterodimer binds E-box elements to transcribe PER1/2/3, CRY1/2, REV-ERBα/β, and ~10% of the transcriptome. CLOCK has intrinsic HAT (histone acetyltransferase) activity acetylating BMAL1-K537 and H3K9. 2017 Nobel.' },
  'ns5b':           { term:'NS5B polymerase', level:'grad', def:'HCV RNA-dependent RNA polymerase — thumb/palm/fingers fold with GDD active site motif. Lacks proofreading → quasispecies diversity. Target of sofosbuvir (UTP analog nucleotide prodrug, chain terminator). NS5B activity is essential; loss-of-function mutations are lethal to virus. 2020 Nobel.' },
  'daa':            { term:'Direct-acting antivirals (DAAs)', level:'grad', def:'HCV drugs targeting viral proteins directly: NS3/4A serine protease inhibitors (glecaprevir, grazoprevir), NS5A replication complex inhibitors (pibrentasvir, ledipasvir), NS5B polymerase inhibitors (sofosbuvir). Pan-genotypic combinations achieve >97% SVR12 — functional cure — in 8-12 weeks. 2020 Nobel downstream.' },
  'ancient_dna':    { term:'Ancient DNA (aDNA)', level:'res', def:'DNA from paleontological/archaeological specimens. Highly fragmented (mean ~50 bp), cytosine deamination at overhangs (C→T at 5\', G→A at 3\') is an authentication signature. Requires strict clean-room extraction, bleach treatment, single-stranded library protocols. Pääbo\'s Vindija Neanderthal genome: ~4 billion bp at 1.3× coverage. 2022 Nobel.' },
  'admixture':      { term:'ADMIXTURE / D-statistics', level:'res', def:'Population genomics tools for detecting archaic admixture. ADMIXTURE (ML) estimates ancestry proportions. D-statistics (ABBA-BABA test) tests for excess shared derived alleles between modern humans and Neanderthals vs outgroup. ~2% Neanderthal ancestry in non-African modern humans, ~4-6% Denisovan in Melanesians. 2022 Nobel.' },
  'alphafold3':     { term:'AlphaFold3 (2024)', level:'frontier', def:'DeepMind diffusion-based model (2024) predicting structures of protein complexes including protein-nucleic acid and protein-small molecule interactions. Enables virtual screening and structure-based drug design without crystallography. Database covers >200M structures. Transforming drug discovery pipeline speed.' },
};
